### ISSUE TITLE
Sometimes @pika/types is not in package-lock.json

### ISSUE THREAD

**Issue by stramel** [pikapkg/pack#23]
Creating an issue for tracking.

I ran into this issue after running,

`npm i -D @pika/pack @pika/plugin-build-node @pika/plugin-web @pika/plugin-ts-standard-pkg`

When running `npm ls @pika/types` I got the following output:

```
$ npm ls @pika/types
js-levenshtein-esm@1.1.6 D:\projects\github\js-levenshtein
+-- @pika/pack@0.3.2
| `-- UNMET DEPENDENCY @pika/types@^0.3.3
+-- @pika/plugin-build-node@0.3.11
| `-- UNMET DEPENDENCY @pika/types@^0.3.5
`-- @pika/plugin-build-web@0.3.11
  `-- UNMET DEPENDENCY @pika/types@^0.3.5

npm ERR! missing: @pika/types@^0.3.3, required by @pika/pack@0.3.2
npm ERR! missing: @pika/types@^0.3.5, required by @pika/plugin-build-node@0.3.11
npm ERR! missing: @pika/types@^0.3.5, required by @pika/plugin-build-web@0.3.11
```

After some effort, I managed to get it in the `package-lock.json` and now `npm ls @pika/types` reports:

```
$ npm ls @pika/types
js-levenshtein-esm@1.1.6 D:\projects\github\js-levenshtein
+-- @pika/pack@0.3.2
| `-- UNMET DEPENDENCY @pika/types@^0.3.3
+-- @pika/plugin-build-node@0.3.11
| `-- UNMET DEPENDENCY @pika/types@^0.3.5
+-- @pika/plugin-build-web@0.3.11
| `-- UNMET DEPENDENCY @pika/types@^0.3.5
`-- @pika/types@0.3.1  extraneous

npm ERR! extraneous: @pika/types@0.3.1 D:\projects\github\js-levenshtein\node_modules\@pika\types
npm ERR! missing: @pika/types@^0.3.3, required by @pika/pack@0.3.2
npm ERR! missing: @pika/types@^0.3.5, required by @pika/plugin-build-node@0.3.11
npm ERR! missing: @pika/types@^0.3.5, required by @pika/plugin-build-web@0.3.11
```

@FredKSchott I'm assuming NPM is trying to optimize by not including `@pika/types` since it sees it as "extraneous"

**Comment by FredKSchott** [comment]
Fixed, looks like lerna was publishing the `types` package with a strange version number. re-installing (and potentially nuking the package-lock) should fix.

**Comment by stramel** [comment]
Thanks!! ♥️

**Comment by kripod** [comment]
This became an issue once again when using the following configuration and `@pika/pack@0.5.0`:

```jsonc
// Excerpt from package.json
{
  "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-ts-standard-pkg"
      ],
      [
        "@pika/plugin-build-web"
      ]
    ]
  },
  "devDependencies": {
    "@pika/plugin-build-web": "^0.6.0",
    "@pika/plugin-ts-standard-pkg": "^0.6.0",
    // ...
  }
}
```

It looks like a [once-working fix](https://github.com/pikapkg/pack/issues/33#issuecomment-469998335) has been reverted.

**Comment by FredKSchott** [comment]
Hmm, I can't reproduce with this package.json in a new directory:

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@pika/pack": "latest",
    "@pika/plugin-build-web": "^0.6.0",
    "@pika/plugin-ts-standard-pkg": "^0.6.0"
  }
}
```

maybe your repo has a bad lock file?

**Comment by kripod** [comment]
@FredKSchott I deleted my lockfile and installed the packages by your given example, but still receiving the error message below:

```
Note: This CLI was recently deprecated. Update your build script to: pika build [flags]
@pika/pack v0.5.0
Error: Cannot find module '@pika/types'
Require stack:
- D:\Development\Projects\standard-hooks\node_modules\@pika\plugin-ts-standard-pkg\dist-node\index.js
- C:\Users\kripod\AppData\Local\Yarn\Data\global\node_modules\import-from\index.js
- C:\Users\kripod\AppData\Local\Yarn\Data\global\node_modules\@pika\pack\dist-node\index.js
- C:\Users\kripod\AppData\Local\Yarn\Data\global\node_modules\@pika\pack\dist-node\index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\Development\Projects\standard-hooks\node_modules\@pika\plugin-ts-standard-pkg\dist-node\index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
```

~Using `@pika/cli` instead of `@pika/pack` seems to solve the issue, though.~
Apparently, `@pika/cli` just fails later.
